### PR TITLE
update dependencies as far as possible without breaking things

### PR DESCRIPTION
**Pull request by lonnen**
per https://github.com/mozilla/sphinx-js/pull/184#issuecomment-1306834468 this PR attempts to update the repository as far as possible without breaking things, given that we've now pinned the most recent working MarkupSafe version. 

It lifts as much as possible out of https://github.com/mozilla/sphinx-js/pull/191, which attempted to start from a more updated version of MarkupSafe and fix all the problems. It has a lot of context about specific issues and incompatibilities.

### CODE REVIEW

**Comment by sylvestre** [comment]
@lonnen can we land this? I would like to update sphinx and it needs a new version of sphinx-js.
Thanks!

**Comment by lonnen** [comment]
Ok, I'll land this with only the updated version of parsimonious and configuration that shifts this off circle-ci (which has stopped working) and onto github actions for tests. This will provide a stable base for future changes but it will be insufficient for getting the other dependencies updated.

**Comment by sylvestre** [comment]
Thanks.
Are you planning to publish a new version soon?

**Comment by lonnen** [comment]
There are a couple of minor issues and ncalexen's [incremental build patch](https://github.com/mozilla/sphinx-js/pull/197) pending. I was planning on waiting until we have support for python3.10 (blocked by https://github.com/mozilla/sphinx-js/issues/209 among other things), but if someone has a need for just the incremental builds work I could go ahead sooner

**Pull request merged**
